### ISSUE TITLE
=。=

### ISSUE THREAD

**Issue by junnplus** [Coderhypo/PlanYourGradePoint#1]
plan 有計算的意思麼？

https://github.com/ma6174/calc_GPA

**Comment by ttop5** [comment]
中式英语233

**Comment by hyponet** [comment]
我还真是计划的意思- -

**Comment by hyponet** [comment]
http://gpa.updev.cn:5000/ @Junnplus  @ttop5

**Comment by junnplus** [comment]
@Coderhypo 噗，打不開

**Comment by hyponet** [comment]
http://gpa.updev.cn/ @Junnplus @ttop5
放在80端口了

**Comment by ttop5** [comment]
72.7：） @Coderhypo

**Comment by hyponet** [comment]
走好不送 _(:з」∠)_
